spring:
  application:
    name: backend
  
  datasource:
    url: jdbc:postgresql://postgres:5432/dms
    username: gopal
    password: maddy8089

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 

jwt:
  secret: your-super-secret-key-must-be-at-least-32-characters-long  

server:
  port: 8080

admin:
  username: daimeera
  password: maddy8089
